#!/usr/bin/env python3
"""Generate the Daily Dit word lists for both ports.

Two lists, from two corpora, because they want opposite things:

  answers  — the daily puzzle words, from a frequency-ordered, profanity-free
             corpus. These are shown to the player, and a daily puzzle everyone
             gets is no place for an obscure or ugly word.
  allowed  — everything a guess may be, from a full dictionary. Wide on purpose:
             being told CRANE "is not a word" is the fastest way to lose a
             player, and the frequency corpus alone rejected it. Guesses never
             leave the device and never appear in the share grid (which is
             emoji), so breadth here costs nothing that answers must pay.

Both are exactly five letters, A-Z only (every letter is sendable in Morse).
Written straight to the Swift and Kotlin sources; the words are never printed
to stdout (only counts), matching gen_words.py.

Usage: gen_dailydit_words.py <out.swift> <out.kt>
"""
import sys
import urllib.request

ANSWER_TARGET = 800

ANSWER_URL = ("https://raw.githubusercontent.com/first20hours/"
              "google-10000-english/master/google-10000-english-usa-no-swears.txt")
ALLOWED_URL = ("https://raw.githubusercontent.com/dwyl/"
               "english-words/master/words_alpha.txt")

ALPHA = set("ABCDEFGHIJKLMNOPQRSTUVWXYZ")


def fetch(url):
    with urllib.request.urlopen(url, timeout=60) as r:
        return r.read().decode("utf-8", "ignore").split()


def five_letter(words):
    """Frequency order preserved, deduped, five letters, A-Z only."""
    out, seen = [], set()
    for w in words:
        u = w.strip().upper()
        if len(u) != 5 or any(ch not in ALPHA for ch in u) or u in seen:
            continue
        seen.add(u)
        out.append(u)
    return out


def rows(words, per_line, indent):
    """Array-literal rows: `"WORD", "WORD", ...`."""
    lines = []
    for i in range(0, len(words), per_line):
        chunk = words[i:i + per_line]
        lines.append(indent + ", ".join(f'"{w}"' for w in chunk) + ",")
    return "\n".join(lines).rstrip(",") + "\n"


def blob(words, per_line, indent):
    """Whitespace-separated rows for the big list, no quotes or commas."""
    lines = []
    for i in range(0, len(words), per_line):
        lines.append(indent + " ".join(words[i:i + per_line]))
    return "\n".join(lines) + "\n"


HEADER = (
    "Word lists for Daily Dit, the shared daily puzzle.\n"
    "\n"
    "`dailyDitAnswers` is the pool the day's word is drawn from, in frequency\n"
    "order, from a profanity-free corpus — these are the words the app shows.\n"
    "`dailyDitAllowed` is every word a guess may be, from a full dictionary and\n"
    "so much wider: a rejected CRANE loses a player faster than a hard word\n"
    "does. Guesses stay on the device and the share grid is emoji, so nothing\n"
    "from this list is ever displayed or transmitted.\n"
    "\n"
    "Auto-generated by tools/gen_dailydit_words.py — do not hand-edit,\n"
    "regenerate instead. Changing `dailyDitAnswers` (its contents OR its order)\n"
    "changes which word every player gets on every future day, so treat a\n"
    "regeneration as a deliberate, announced change: fixtures/daily-dit.json\n"
    "pins real words and will fail first.\n"
)

BLOB_NOTE_SWIFT = """
    /// Held as one whitespace-separated blob and split on first use, not as an
    /// array literal. {n:,} string literals in a single array is the Swift type
    /// checker's worst case — this is one literal, and `static let` splits it
    /// lazily, once.
"""

BLOB_NOTE_KOTLIN = """
/**
 * Held as one whitespace-separated blob and split on first use, mirroring the
 * Swift side: {n:,} quoted entries in one `listOf` is a needlessly large thing
 * to hand a compiler when one raw string does.
 */
"""


def comment(prefix):
    return "".join(f"{prefix} {ln}\n" if ln else f"{prefix}\n"
                   for ln in HEADER.split("\n")[:-1])


def swift_source(answers, allowed):
    return (
        "import Foundation\n\n"
        + comment("//")
        + "\nextension MorseData {\n"
        f"    /// {len(answers)} five-letter answers, most common first.\n"
        "    public static let dailyDitAnswers: [String] = [\n"
        f"{rows(answers, 10, '        ')}"
        "    ]\n"
        f"\n    /// {len(allowed)} five-letter words accepted as a guess."
        + BLOB_NOTE_SWIFT.format(n=len(allowed)) +
        "    public static let dailyDitAllowed: [String] =\n"
        "        dailyDitAllowedBlob.split(whereSeparator: \\.isWhitespace).map(String.init)\n"
        "\n    private static let dailyDitAllowedBlob = \"\"\"\n"
        f"{blob(allowed, 12, '        ')}"
        "        \"\"\"\n"
        "}\n"
    )


def kotlin_source(answers, allowed):
    return (
        "package app.anothermorsetrainer.morsekit\n\n"
        + comment("//")
        + "//\n"
        "// Translated from MorseKit/DailyDitWords.swift. Swift attaches these to\n"
        "// MorseData via an extension; Kotlin objects can't be split across files,\n"
        "// so they live here as internal top-level vals and MorseData re-exposes them.\n"
        f"\n/** {len(answers)} five-letter answers, most common first. */\n"
        "internal val dailyDitAnswersData: List<String> = listOf(\n"
        f"{rows(answers, 10, '    ')}"
        ")\n"
        + BLOB_NOTE_KOTLIN.format(n=len(allowed)) +
        "private val dailyDitAllowedBlob: String = \"\"\"\n"
        f"{blob(allowed, 12, '')}"
        "\"\"\"\n"
        f"\n/** {len(allowed)} five-letter words accepted as a guess. */\n"
        "internal val dailyDitAllowedData: List<String> =\n"
        "    dailyDitAllowedBlob.split(Regex(\"\\\\s+\")).filter { it.isNotEmpty() }\n"
    )


def main():
    if len(sys.argv) != 3:
        sys.stderr.write(__doc__)
        sys.exit(2)
    answers = five_letter(fetch(ANSWER_URL))[:ANSWER_TARGET]
    if len(answers) < ANSWER_TARGET:
        sys.stderr.write(f"only got {len(answers)} answer words; aborting\n")
        sys.exit(1)
    # Answers are folded in so the day's word is always a legal guess even if
    # the dictionary and the frequency corpus disagree about it.
    allowed = sorted(set(five_letter(fetch(ALLOWED_URL))) | set(answers))
    if len(allowed) < 5000:
        sys.stderr.write(f"only got {len(allowed)} allowed words; aborting\n")
        sys.exit(1)
    with open(sys.argv[1], "w") as f:
        f.write(swift_source(answers, allowed))
    with open(sys.argv[2], "w") as f:
        f.write(kotlin_source(answers, allowed))
    print(f"OK wrote {len(answers)} answers / {len(allowed)} allowed guesses")


if __name__ == "__main__":
    main()
