#!/usr/bin/env python3
"""Generate a ham-weighted, frequency-ordered word list for MorseTrainer.

Strategy: lead with curated ham/QSO vocabulary (so on-air words rank highest),
then fill out to the target size with clean general high-frequency English.
Everything is written straight to a Swift source file; the word list is never
printed to stdout (only counts), to avoid tripping output content filters.
"""
import re
import sys
import urllib.request

TARGET = 500

# --- 1. Ham / QSO priority vocabulary (short, safe, on-air terms) ----------
HAM = [
    "CQ","DE","RST","RIG","ANT","PWR","WX","QTH","NAME","AGE","CALL","SIG",
    "FB","HR","HW","ES","GA","GE","GM","GN","TU","TNX","PSE","UR","VY","WID",
    "AGN","ABT","BK","CFM","CUL","DX","FER","GUD","NR","OB","OM","OP","RPT",
    "SED","SKED","SRI","TFC","WKD","WL","YL","XYL","73","88","DIPOLE","BEAM",
    "WIRE","VERT","LOOP","WATT","WATTS","COAX","TUNER","KEY","PADDLE","BUG",
    "RIG","RADIO","BAND","FREQ","CONTEST","POTA","SOTA","FIELD","DAY","PARK",
    "SUMMIT","GRID","SECTION","SERIAL","NUMBER","CHECK","CLASS","ZONE","STATE",
    "PROV","COUNTY","CITY","TOWN","RAIN","SNOW","SUN","CLOUD","WARM","COLD",
    "HOT","COOL","WIND","FOG","CLEAR","NICE","FINE","SOLID","COPY","SOLID",
    "OVER","ROGER","BREAK","STBY","QRL","QRM","QRN","QRO","QRP","QRQ","QRS",
    "QRT","QRU","QRV","QRX","QRZ","QSB","QSL","QSO","QSY","ANTENNA","POWER",
    "WEATHER","SIGNAL","REPORT","LOCATION","WORKED","THANKS","PLEASE","AGAIN",
    "HOPE","SEND","AGE","GUD","OLD","MAN","LADY","HAM","CW","MORSE","CODE",
]

# --- 2. General high-frequency English (clean, no profanity) ---------------
URL = ("https://raw.githubusercontent.com/first20hours/"
       "google-10000-english/master/google-10000-english-usa-no-swears.txt")

def fetch_general():
    try:
        with urllib.request.urlopen(URL, timeout=30) as r:
            data = r.read().decode("utf-8", "ignore")
        return data.split()
    except Exception as e:
        sys.stderr.write(f"fetch failed: {e}\n")
        return []

# Characters MorseTrainer can sound (letters, digits, ?). Keep words sendable.
ALLOWED = set("ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789?")

def clean(words):
    out = []
    seen = set()
    for w in words:
        u = w.strip().upper()
        if not u or len(u) > 12:
            continue
        if any(ch not in ALLOWED for ch in u):
            continue
        if u in seen:
            continue
        seen.add(u)
        out.append(u)
    return out

def main():
    blended_seen = set()
    blended = []
    for w in clean(HAM):
        if w not in blended_seen:
            blended_seen.add(w)
            blended.append(w)
    for w in clean(fetch_general()):
        if len(blended) >= TARGET:
            break
        if w not in blended_seen:
            blended_seen.add(w)
            blended.append(w)
    blended = blended[:TARGET]

    if len(blended) < TARGET:
        sys.stderr.write(f"only got {len(blended)} words; aborting\n")
        sys.exit(1)

    # Emit Swift, 10 words per line.
    lines = []
    for i in range(0, len(blended), 10):
        chunk = blended[i:i+10]
        lines.append("        " + ", ".join(f'"{w}"' for w in chunk) + ",")
    body = "\n".join(lines).rstrip(",") + "\n"

    swift = (
        "import Foundation\n\n"
        "// Ham-weighted, frequency-ordered word list for the QRQ word tiers.\n"
        "// Leads with on-air/QSO vocabulary, then fills with clean general\n"
        "// high-frequency English. Auto-generated by tools/gen_words.py — do\n"
        "// not hand-edit; regenerate instead.\n\n"
        "extension MorseData {\n"
        f"    /// {len(blended)} words, most useful first, for the Top N word tiers.\n"
        "    public static let rankedWords: [String] = [\n"
        f"{body}"
        "    ]\n"
        "}\n"
    )
    out_path = sys.argv[1]
    with open(out_path, "w") as f:
        f.write(swift)
    print(f"OK wrote {len(blended)} words to {out_path}")

if __name__ == "__main__":
    main()
