package app.anothermorsetrainer.morsekit

// Curated on-air QSO vocabulary for Listen & Learn's "QSO elements" tiers
// (#182). One ordered list, most common first, so Top 20 is the first twenty
// and Top 100 is the whole list. Pinned for both ports by
// fixtures/qso-elements.json — change the list there and here together.
//
// Token spelling: letters, digits, ? and / are sent as text and a space is a
// word gap; a token in angle brackets is a prosign spelled exactly as
// [MorseData.prosigns] spells it and is sent run-together from that table's
// pattern. Meanings repeat the wording of `abbreviations` / `qCodes` /
// `prosigns` wherever the token already lives there.
//
// Translated from MorseKit/MorseDataQSO.swift. Swift attaches this to
// MorseData via an extension; Kotlin objects can't be split across files,
// so it lives here as an internal top-level val and MorseData re-exposes it.

/** The 100 most-heard on-air QSO elements, most common first. */
internal val qsoElementsData: List<TokenMeaning> = listOf(
    // Top 20: the skeleton of every contact.
    TokenMeaning("CQ", "calling any station"),
    TokenMeaning("DE", "this is / from"),
    TokenMeaning("<K>", "go ahead — any station"),
    TokenMeaning("<KN>", "go ahead — named station only"),
    TokenMeaning("<AR>", "over — end of message"),
    TokenMeaning("<SK>", "end of contact"),
    TokenMeaning("<BK>", "break — back to you"),
    TokenMeaning("TU", "thank you"),
    TokenMeaning("73", "best regards"),
    TokenMeaning("RST", "signal report"),
    TokenMeaning("599", "five nine nine — a perfect signal report"),
    TokenMeaning("5NN", "five nine nine, with N cut for 9"),
    TokenMeaning("UR", "your / you're"),
    TokenMeaning("NAME", "name"),
    TokenMeaning("QTH", "my location is"),
    TokenMeaning("HR", "here"),
    TokenMeaning("ES", "and"),
    TokenMeaning("HW?", "how do you copy?"),
    TokenMeaning("R", "received / roger"),
    TokenMeaning("TNX", "thanks"),
    // 21–100: the rest of a ragchew, a DX exchange and the weather.
    TokenMeaning("QSL", "acknowledge / received"),
    TokenMeaning("QRZ?", "who is calling me?"),
    TokenMeaning("QRL?", "is this frequency in use?"),
    TokenMeaning("AGN", "again"),
    TokenMeaning("PSE", "please"),
    TokenMeaning("RIG", "radio"),
    TokenMeaning("ANT", "antenna"),
    TokenMeaning("WX", "weather"),
    TokenMeaning("OM", "old man"),
    TokenMeaning("YL", "young lady"),
    TokenMeaning("XYL", "wife (ex young lady)"),
    TokenMeaning("GM", "good morning"),
    TokenMeaning("GA", "good afternoon"),
    TokenMeaning("GE", "good evening"),
    TokenMeaning("GN", "good night"),
    TokenMeaning("CUL", "see you later"),
    TokenMeaning("CUAGN", "see you again"),
    TokenMeaning("DX", "distance"),
    TokenMeaning("FB", "fine business (great)"),
    TokenMeaning("GUD", "good"),
    TokenMeaning("VY", "very"),
    TokenMeaning("ABT", "about"),
    TokenMeaning("CPY", "copy"),
    TokenMeaning("HW", "how do you copy"),
    TokenMeaning("NW", "now"),
    TokenMeaning("WID", "with"),
    TokenMeaning("PWR", "power"),
    TokenMeaning("WATTS", "watts"),
    TokenMeaning("DIPOLE", "dipole antenna"),
    TokenMeaning("VERT", "vertical antenna"),
    TokenMeaning("YAGI", "Yagi beam antenna"),
    TokenMeaning("TEMP", "temperature"),
    TokenMeaning("DEG", "degrees"),
    TokenMeaning("SUNNY", "sunny"),
    TokenMeaning("CLDY", "cloudy"),
    TokenMeaning("RAIN", "rain"),
    TokenMeaning("QRM", "man-made interference"),
    TokenMeaning("QRN", "atmospheric noise / static"),
    TokenMeaning("QSB", "your signals are fading"),
    TokenMeaning("QRS", "send slower"),
    TokenMeaning("QRQ", "send faster"),
    TokenMeaning("QRP", "low power"),
    TokenMeaning("QRO", "increase power"),
    TokenMeaning("QRT", "stop sending / going off air"),
    TokenMeaning("QRV", "I am ready"),
    TokenMeaning("QRX", "wait / stand by"),
    TokenMeaning("QSY", "change frequency"),
    TokenMeaning("QSO", "a contact"),
    TokenMeaning("QRZ", "who is calling me?"),
    TokenMeaning("QRL", "this frequency is busy / in use"),
    TokenMeaning("QSK", "full break-in"),
    TokenMeaning("BTU", "back to you"),
    TokenMeaning("HPE", "hope"),
    TokenMeaning("SRI", "sorry"),
    TokenMeaning("TKS", "thanks"),
    TokenMeaning("RR", "roger roger — all received"),
    TokenMeaning("TEST", "contest — calling CQ contest"),
    TokenMeaning("BCNU", "be seeing you"),
    TokenMeaning("CU", "see you"),
    TokenMeaning("NR", "number"),
    TokenMeaning("NIL", "nothing received"),
    TokenMeaning("OK", "okay"),
    TokenMeaning("FER", "for"),
    TokenMeaning("HI", "laughter"),
    TokenMeaning("MNI", "many"),
    TokenMeaning("RPT", "repeat / report"),
    TokenMeaning("SIG", "signal"),
    TokenMeaning("SKED", "schedule"),
    TokenMeaning("SN", "soon"),
    TokenMeaning("TMW", "tomorrow"),
    TokenMeaning("WKD", "worked"),
    TokenMeaning("WL", "well"),
    TokenMeaning("88", "love and kisses"),
    TokenMeaning("CONDX", "conditions"),
    TokenMeaning("OP", "operator"),
    TokenMeaning("HV", "have"),
    TokenMeaning("GL", "good luck"),
    TokenMeaning("CQ CQ CQ", "calling any station — the full call"),
    TokenMeaning("TNX FER CALL", "thanks for the call"),
    TokenMeaning("5NN TU", "five nine nine, thank you — the contest exchange")
)
