import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import javax.xml.parsers.DocumentBuilderFactory

plugins {
    kotlin("jvm")
    id("org.jetbrains.kotlin.plugin.compose")
    id("org.jetbrains.compose")
}

// ---- Version ----
// The shared app version, the same on every platform (CLAUDE.md, "Versions,
// tags, CI"); desktopVersionCode is desktop's own build counter.
// jpackage's MSI wants MAJOR.MINOR.PATCH with MAJOR > 0; the MSIX manifest
// wants four parts with the last one 0 (the Store reserves it), so the MSIX
// version is "$desktopVersionName.0" and every Store submission moves PATCH.
// Release tags are desktop-v<versionName>.
val desktopVersionName = "2.0.0"
val desktopVersionCode = 3

kotlin {
    jvmToolchain(21)
}

dependencies {
    implementation(compose.desktop.currentOs)
    // Material 3 and the icon set are versioned apart from the Compose UI
    // runtime since CMP 1.8. 1.9.0 is the Material 3 release built against
    // CMP 1.9; material-icons-extended stopped at 1.7.3 and is still what the
    // plugin's own accessor resolves to.
    implementation("org.jetbrains.compose.material3:material3:1.9.0")
    implementation("org.jetbrains.compose.material:material-icons-extended:1.7.3")
    // Dispatchers.Main on the AWT event thread, which is Compose Desktop's UI thread.
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.10.2")
    // Android has org.json in the platform; the JVM does not, and the stores
    // persist through it exactly as the Android port does.
    implementation("org.json:json:20260814")
    // WebSocket transport for the Vail repeater client, the leaderboard and
    // the Short Stories news fetch. Same library and version as android/.
    implementation("com.squareup.okhttp3:okhttp:4.12.0")

    testImplementation("junit:junit:4.13.2")
}

// ---- Shared fixtures, as test data only (CLAUDE.md, "two ports, not one") ----
sourceSets {
    test {
        resources.srcDir(rootProject.file("../fixtures"))
    }
}

// ---- Generated sources: R ids for the string table, and build info ----
//
// The UI was ported from android/, where copy lives in res/values/strings.xml
// and code says stringResource(R.string.foo). The desktop tree keeps the same
// file (src/main/resources/values/strings.xml) and the same call shape: this
// task writes an R object with one Int per entry plus the entry names, and
// Strings.kt loads the XML from the classpath and resolves by name. The file
// is a copy, not a link; the two trees' copy drifts only by deliberate edit.
val generatedDir = layout.buildDirectory.dir("generated/amt/kotlin")
val stringsXml = file("src/main/resources/values/strings.xml")

val generateAmtSources by tasks.registering {
    inputs.file(stringsXml)
    inputs.property("versionName", desktopVersionName)
    inputs.property("versionCode", desktopVersionCode)
    outputs.dir(generatedDir)
    doLast {
        val doc = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(stringsXml)
        fun names(tag: String): List<String> {
            val nodes = doc.getElementsByTagName(tag)
            return (0 until nodes.length).map { nodes.item(it).attributes.getNamedItem("name").nodeValue }
        }
        val kinds = listOf("string" to "string", "plurals" to "plurals", "string-array" to "array")
        val out = StringBuilder()
        out.append("// Generated by :app:generateAmtSources from values/strings.xml. Do not edit.\n")
        out.append("package app.anothermorsetrainer\n\n")
        out.append("@Suppress(\"ClassName\", \"ObjectPropertyName\")\n")
        out.append("object R {\n")
        for ((tag, obj) in kinds) {
            val list = names(tag)
            out.append("    object $obj {\n")
            list.forEachIndexed { i, n -> out.append("        const val `$n`: Int = $i\n") }
            out.append("        val names: Array<String> = arrayOf(\n")
            list.forEach { n -> out.append("            \"$n\",\n") }
            out.append("        )\n    }\n")
        }
        out.append("}\n")
        val dir = generatedDir.get().asFile.resolve("app/anothermorsetrainer")
        dir.mkdirs()
        dir.resolve("R.kt").writeText(out.toString())
        dir.resolve("BuildInfo.kt").writeText(
            "// Generated by :app:generateAmtSources. Do not edit.\n" +
                "package app.anothermorsetrainer\n\n" +
                "object BuildInfo {\n" +
                "    const val VERSION_NAME: String = \"$desktopVersionName\"\n" +
                "    const val VERSION_CODE: Int = $desktopVersionCode\n" +
                "}\n"
        )
    }
}

kotlin.sourceSets.named("main") {
    kotlin.srcDir(generatedDir)
}
tasks.named("compileKotlin") { dependsOn(generateAmtSources) }

tasks.test {
    // Name every test in the log, passed or failed, so a green run shows what
    // ran (CLAUDE.md, "Verifying a change here", rule 2 still applies).
    testLogging {
        events("passed", "skipped", "failed")
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
    }
}

// ---- Native distributions (jpackage) ----
compose.desktop {
    application {
        mainClass = "app.anothermorsetrainer.MainKt"
        jvmArgs += listOf("-Xmx768m", "-Dfile.encoding=UTF-8")

        nativeDistributions {
            // MSI for the GitHub Releases download; the Store build is an MSIX
            // made from the app image by makeappx (desktop.yml). Deb is not
            // shipped, but costs nothing and is the quickest local install
            // check on a Debian-family machine. Linux ships as Flatpak and
            // AppImage, both built from createDistributable's app image.
            targetFormats(TargetFormat.Msi, TargetFormat.Deb)
            packageName = "AnotherMorseTrainer"
            packageVersion = desktopVersionName
            description = "Learn and practise Morse code"
            vendor = "Justin Rogers"
            copyright = "Copyright (C) 2026 Justin Rogers. GPL-3.0-or-later."
            licenseFile.set(rootProject.file("../LICENSE"))

            // jlink's module list. Missing one is a runtime ClassNotFound, not
            // a build error: java.desktop is Swing/AWT and javax.sound;
            // jdk.crypto.ec is TLS for OkHttp on JDK 21; java.prefs and
            // jdk.unsupported are pulled in by Compose/Skiko; java.naming by
            // OkHttp's platform probe.
            modules(
                "java.desktop", "java.logging", "java.naming", "java.net.http",
                "java.prefs", "java.xml", "jdk.crypto.ec", "jdk.unsupported",
                "jdk.accessibility"
            )

            windows {
                menuGroup = "Another Morse Trainer"
                perUserInstall = true
                shortcut = true
                dirChooser = false
                // Fixed forever: the MSI upgrade code is how Windows knows a
                // new MSI replaces the old install. Never change it.
                upgradeUuid = "6f0d3c1e-8a2b-4f5e-9c47-2d8e1b6a0f35"
                iconFile.set(rootProject.file("packaging/icons/icon.ico"))
            }
            linux {
                packageName = "another-morse-trainer"
                iconFile.set(rootProject.file("packaging/icons/icon-512.png"))
                menuGroup = "Education"
                appCategory = "Education"
            }
        }
    }
}
